---
development:
  cloud_name: <%= ENV["namdq"] %>
  api_key: <%= ENV["218781116725348"] %>
  api_secret: <%= ENV["0ngv5Oc0YXXTSFudfptJi6T1RWQ"] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: <%= ENV["namdq"] %>
  api_key: <%= ENV["218781116725348"] %>
  api_secret: <%= ENV["0ngv5Oc0YXXTSFudfptJi6T1RWQ"] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: <%= ENV["namdq"] %>
  api_key: <%= ENV["218781116725348"] %>
  api_secret: <%= ENV["0ngv5Oc0YXXTSFudfptJi6T1RWQ"] %>
  enhance_image_tag: true
  static_image_support: false
